// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *ServerConfig          `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Repo          *RepoConfig            `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_internal_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_internal_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetServer() *ServerConfig {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Config) GetRepo() *RepoConfig {
	if x != nil {
		return x.Repo
	}
	return nil
}

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          string                 `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	GrpcPort      string                 `protobuf:"bytes,2,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_internal_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ServerConfig) GetGrpcPort() string {
	if x != nil {
		return x.GrpcPort
	}
	return ""
}

type RepoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoConfig) Reset() {
	*x = RepoConfig{}
	mi := &file_internal_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoConfig) ProtoMessage() {}

func (x *RepoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoConfig.ProtoReflect.Descriptor instead.
func (*RepoConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *RepoConfig) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

var File_internal_proto_config_proto protoreflect.FileDescriptor

const file_internal_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/config.proto\x12\x05proto\"\\\n" +
	"\x06Config\x12+\n" +
	"\x06server\x18\x01 \x01(\v2\x13.proto.ServerConfigR\x06server\x12%\n" +
	"\x04repo\x18\x02 \x01(\v2\x11.proto.RepoConfigR\x04repo\"?\n" +
	"\fServerConfig\x12\x12\n" +
	"\x04port\x18\x01 \x01(\tR\x04port\x12\x1b\n" +
	"\tgrpc_port\x18\x02 \x01(\tR\bgrpcPort\"\x1e\n" +
	"\n" +
	"RepoConfig\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dirB\x16Z\x14mitra/internal/protob\x06proto3"

var (
	file_internal_proto_config_proto_rawDescOnce sync.Once
	file_internal_proto_config_proto_rawDescData []byte
)

func file_internal_proto_config_proto_rawDescGZIP() []byte {
	file_internal_proto_config_proto_rawDescOnce.Do(func() {
		file_internal_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_config_proto_rawDesc), len(file_internal_proto_config_proto_rawDesc)))
	})
	return file_internal_proto_config_proto_rawDescData
}

var file_internal_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_config_proto_goTypes = []any{
	(*Config)(nil),       // 0: proto.Config
	(*ServerConfig)(nil), // 1: proto.ServerConfig
	(*RepoConfig)(nil),   // 2: proto.RepoConfig
}
var file_internal_proto_config_proto_depIdxs = []int32{
	1, // 0: proto.Config.server:type_name -> proto.ServerConfig
	2, // 1: proto.Config.repo:type_name -> proto.RepoConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_config_proto_init() }
func file_internal_proto_config_proto_init() {
	if File_internal_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_config_proto_rawDesc), len(file_internal_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_config_proto_goTypes,
		DependencyIndexes: file_internal_proto_config_proto_depIdxs,
		MessageInfos:      file_internal_proto_config_proto_msgTypes,
	}.Build()
	File_internal_proto_config_proto = out.File
	file_internal_proto_config_proto_goTypes = nil
	file_internal_proto_config_proto_depIdxs = nil
}
