// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/mitra.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_internal_proto_mitra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Repo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Repo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Repo) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type Worktree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoId        string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	IsMain        bool                   `protobuf:"varint,5,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	ParentBranch  *string                `protobuf:"bytes,6,opt,name=parent_branch,json=parentBranch,proto3,oneof" json:"parent_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worktree) Reset() {
	*x = Worktree{}
	mi := &file_internal_proto_mitra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worktree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worktree) ProtoMessage() {}

func (x *Worktree) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worktree.ProtoReflect.Descriptor instead.
func (*Worktree) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{1}
}

func (x *Worktree) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worktree) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Worktree) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Worktree) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Worktree) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

func (x *Worktree) GetParentBranch() string {
	if x != nil && x.ParentBranch != nil {
		return *x.ParentBranch
	}
	return ""
}

type ListReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposRequest) Reset() {
	*x = ListReposRequest{}
	mi := &file_internal_proto_mitra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposRequest) ProtoMessage() {}

func (x *ListReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposRequest.ProtoReflect.Descriptor instead.
func (*ListReposRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{2}
}

type ListReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repo                `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposResponse) Reset() {
	*x = ListReposResponse{}
	mi := &file_internal_proto_mitra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposResponse) ProtoMessage() {}

func (x *ListReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposResponse.ProtoReflect.Descriptor instead.
func (*ListReposResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{3}
}

func (x *ListReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type AddRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRepoRequest) Reset() {
	*x = AddRepoRequest{}
	mi := &file_internal_proto_mitra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRepoRequest) ProtoMessage() {}

func (x *AddRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRepoRequest.ProtoReflect.Descriptor instead.
func (*AddRepoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{4}
}

func (x *AddRepoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repo                  `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRepoResponse) Reset() {
	*x = AddRepoResponse{}
	mi := &file_internal_proto_mitra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRepoResponse) ProtoMessage() {}

func (x *AddRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRepoResponse.ProtoReflect.Descriptor instead.
func (*AddRepoResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{5}
}

func (x *AddRepoResponse) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

type CreateWorktreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	ParentBranch  *string                `protobuf:"bytes,3,opt,name=parent_branch,json=parentBranch,proto3,oneof" json:"parent_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorktreeRequest) Reset() {
	*x = CreateWorktreeRequest{}
	mi := &file_internal_proto_mitra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorktreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorktreeRequest) ProtoMessage() {}

func (x *CreateWorktreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorktreeRequest.ProtoReflect.Descriptor instead.
func (*CreateWorktreeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorktreeRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CreateWorktreeRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateWorktreeRequest) GetParentBranch() string {
	if x != nil && x.ParentBranch != nil {
		return *x.ParentBranch
	}
	return ""
}

type CreateWorktreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worktree      *Worktree              `protobuf:"bytes,1,opt,name=worktree,proto3" json:"worktree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorktreeResponse) Reset() {
	*x = CreateWorktreeResponse{}
	mi := &file_internal_proto_mitra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorktreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorktreeResponse) ProtoMessage() {}

func (x *CreateWorktreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorktreeResponse.ProtoReflect.Descriptor instead.
func (*CreateWorktreeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWorktreeResponse) GetWorktree() *Worktree {
	if x != nil {
		return x.Worktree
	}
	return nil
}

type ListWorktreesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesRequest) Reset() {
	*x = ListWorktreesRequest{}
	mi := &file_internal_proto_mitra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesRequest) ProtoMessage() {}

func (x *ListWorktreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesRequest.ProtoReflect.Descriptor instead.
func (*ListWorktreesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorktreesRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type ListWorktreesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worktrees     []*Worktree            `protobuf:"bytes,1,rep,name=worktrees,proto3" json:"worktrees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesResponse) Reset() {
	*x = ListWorktreesResponse{}
	mi := &file_internal_proto_mitra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesResponse) ProtoMessage() {}

func (x *ListWorktreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mitra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesResponse.ProtoReflect.Descriptor instead.
func (*ListWorktreesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_mitra_proto_rawDescGZIP(), []int{9}
}

func (x *ListWorktreesResponse) GetWorktrees() []*Worktree {
	if x != nil {
		return x.Worktrees
	}
	return nil
}

var File_internal_proto_mitra_proto protoreflect.FileDescriptor

const file_internal_proto_mitra_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/mitra.proto\x12\x05proto\"f\n" +
	"\x04Repo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x05 \x01(\tR\x04repo\"\xb4\x01\n" +
	"\bWorktree\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x17\n" +
	"\ais_main\x18\x05 \x01(\bR\x06isMain\x12(\n" +
	"\rparent_branch\x18\x06 \x01(\tH\x00R\fparentBranch\x88\x01\x01B\x10\n" +
	"\x0e_parent_branch\"\x12\n" +
	"\x10ListReposRequest\"6\n" +
	"\x11ListReposResponse\x12!\n" +
	"\x05repos\x18\x01 \x03(\v2\v.proto.RepoR\x05repos\"\"\n" +
	"\x0eAddRepoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"2\n" +
	"\x0fAddRepoResponse\x12\x1f\n" +
	"\x04repo\x18\x01 \x01(\v2\v.proto.RepoR\x04repo\"\x84\x01\n" +
	"\x15CreateWorktreeRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12(\n" +
	"\rparent_branch\x18\x03 \x01(\tH\x00R\fparentBranch\x88\x01\x01B\x10\n" +
	"\x0e_parent_branch\"E\n" +
	"\x16CreateWorktreeResponse\x12+\n" +
	"\bworktree\x18\x01 \x01(\v2\x0f.proto.WorktreeR\bworktree\"/\n" +
	"\x14ListWorktreesRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\"F\n" +
	"\x15ListWorktreesResponse\x12-\n" +
	"\tworktrees\x18\x01 \x03(\v2\x0f.proto.WorktreeR\tworktrees2\xa3\x02\n" +
	"\fMitraService\x12>\n" +
	"\tListRepos\x12\x17.proto.ListReposRequest\x1a\x18.proto.ListReposResponse\x128\n" +
	"\aAddRepo\x12\x15.proto.AddRepoRequest\x1a\x16.proto.AddRepoResponse\x12M\n" +
	"\x0eCreateWorktree\x12\x1c.proto.CreateWorktreeRequest\x1a\x1d.proto.CreateWorktreeResponse\x12J\n" +
	"\rListWorktrees\x12\x1b.proto.ListWorktreesRequest\x1a\x1c.proto.ListWorktreesResponseB\x16Z\x14mitra/internal/protob\x06proto3"

var (
	file_internal_proto_mitra_proto_rawDescOnce sync.Once
	file_internal_proto_mitra_proto_rawDescData []byte
)

func file_internal_proto_mitra_proto_rawDescGZIP() []byte {
	file_internal_proto_mitra_proto_rawDescOnce.Do(func() {
		file_internal_proto_mitra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_mitra_proto_rawDesc), len(file_internal_proto_mitra_proto_rawDesc)))
	})
	return file_internal_proto_mitra_proto_rawDescData
}

var file_internal_proto_mitra_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_mitra_proto_goTypes = []any{
	(*Repo)(nil),                   // 0: proto.Repo
	(*Worktree)(nil),               // 1: proto.Worktree
	(*ListReposRequest)(nil),       // 2: proto.ListReposRequest
	(*ListReposResponse)(nil),      // 3: proto.ListReposResponse
	(*AddRepoRequest)(nil),         // 4: proto.AddRepoRequest
	(*AddRepoResponse)(nil),        // 5: proto.AddRepoResponse
	(*CreateWorktreeRequest)(nil),  // 6: proto.CreateWorktreeRequest
	(*CreateWorktreeResponse)(nil), // 7: proto.CreateWorktreeResponse
	(*ListWorktreesRequest)(nil),   // 8: proto.ListWorktreesRequest
	(*ListWorktreesResponse)(nil),  // 9: proto.ListWorktreesResponse
}
var file_internal_proto_mitra_proto_depIdxs = []int32{
	0, // 0: proto.ListReposResponse.repos:type_name -> proto.Repo
	0, // 1: proto.AddRepoResponse.repo:type_name -> proto.Repo
	1, // 2: proto.CreateWorktreeResponse.worktree:type_name -> proto.Worktree
	1, // 3: proto.ListWorktreesResponse.worktrees:type_name -> proto.Worktree
	2, // 4: proto.MitraService.ListRepos:input_type -> proto.ListReposRequest
	4, // 5: proto.MitraService.AddRepo:input_type -> proto.AddRepoRequest
	6, // 6: proto.MitraService.CreateWorktree:input_type -> proto.CreateWorktreeRequest
	8, // 7: proto.MitraService.ListWorktrees:input_type -> proto.ListWorktreesRequest
	3, // 8: proto.MitraService.ListRepos:output_type -> proto.ListReposResponse
	5, // 9: proto.MitraService.AddRepo:output_type -> proto.AddRepoResponse
	7, // 10: proto.MitraService.CreateWorktree:output_type -> proto.CreateWorktreeResponse
	9, // 11: proto.MitraService.ListWorktrees:output_type -> proto.ListWorktreesResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_mitra_proto_init() }
func file_internal_proto_mitra_proto_init() {
	if File_internal_proto_mitra_proto != nil {
		return
	}
	file_internal_proto_mitra_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_proto_mitra_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_mitra_proto_rawDesc), len(file_internal_proto_mitra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_mitra_proto_goTypes,
		DependencyIndexes: file_internal_proto_mitra_proto_depIdxs,
		MessageInfos:      file_internal_proto_mitra_proto_msgTypes,
	}.Build()
	File_internal_proto_mitra_proto = out.File
	file_internal_proto_mitra_proto_goTypes = nil
	file_internal_proto_mitra_proto_depIdxs = nil
}
