// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/proto/mitra.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MitraService_ListRepos_FullMethodName     = "/proto.MitraService/ListRepos"
	MitraService_AddRepo_FullMethodName       = "/proto.MitraService/AddRepo"
	MitraService_AddWorktree_FullMethodName   = "/proto.MitraService/AddWorktree"
	MitraService_ListWorktrees_FullMethodName = "/proto.MitraService/ListWorktrees"
)

// MitraServiceClient is the client API for MitraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MitraServiceClient interface {
	ListRepos(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error)
	AddRepo(ctx context.Context, in *AddRepoRequest, opts ...grpc.CallOption) (*AddRepoResponse, error)
	AddWorktree(ctx context.Context, in *AddWorktreeRequest, opts ...grpc.CallOption) (*AddWorktreeResponse, error)
	ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error)
}

type mitraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMitraServiceClient(cc grpc.ClientConnInterface) MitraServiceClient {
	return &mitraServiceClient{cc}
}

func (c *mitraServiceClient) ListRepos(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReposResponse)
	err := c.cc.Invoke(ctx, MitraService_ListRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mitraServiceClient) AddRepo(ctx context.Context, in *AddRepoRequest, opts ...grpc.CallOption) (*AddRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRepoResponse)
	err := c.cc.Invoke(ctx, MitraService_AddRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mitraServiceClient) AddWorktree(ctx context.Context, in *AddWorktreeRequest, opts ...grpc.CallOption) (*AddWorktreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWorktreeResponse)
	err := c.cc.Invoke(ctx, MitraService_AddWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mitraServiceClient) ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorktreesResponse)
	err := c.cc.Invoke(ctx, MitraService_ListWorktrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MitraServiceServer is the server API for MitraService service.
// All implementations must embed UnimplementedMitraServiceServer
// for forward compatibility.
type MitraServiceServer interface {
	ListRepos(context.Context, *ListReposRequest) (*ListReposResponse, error)
	AddRepo(context.Context, *AddRepoRequest) (*AddRepoResponse, error)
	AddWorktree(context.Context, *AddWorktreeRequest) (*AddWorktreeResponse, error)
	ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error)
	mustEmbedUnimplementedMitraServiceServer()
}

// UnimplementedMitraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMitraServiceServer struct{}

func (UnimplementedMitraServiceServer) ListRepos(context.Context, *ListReposRequest) (*ListReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepos not implemented")
}
func (UnimplementedMitraServiceServer) AddRepo(context.Context, *AddRepoRequest) (*AddRepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRepo not implemented")
}
func (UnimplementedMitraServiceServer) AddWorktree(context.Context, *AddWorktreeRequest) (*AddWorktreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWorktree not implemented")
}
func (UnimplementedMitraServiceServer) ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorktrees not implemented")
}
func (UnimplementedMitraServiceServer) mustEmbedUnimplementedMitraServiceServer() {}
func (UnimplementedMitraServiceServer) testEmbeddedByValue()                      {}

// UnsafeMitraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MitraServiceServer will
// result in compilation errors.
type UnsafeMitraServiceServer interface {
	mustEmbedUnimplementedMitraServiceServer()
}

func RegisterMitraServiceServer(s grpc.ServiceRegistrar, srv MitraServiceServer) {
	// If the following call panics, it indicates UnimplementedMitraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MitraService_ServiceDesc, srv)
}

func _MitraService_ListRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MitraServiceServer).ListRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MitraService_ListRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MitraServiceServer).ListRepos(ctx, req.(*ListReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MitraService_AddRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MitraServiceServer).AddRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MitraService_AddRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MitraServiceServer).AddRepo(ctx, req.(*AddRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MitraService_AddWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MitraServiceServer).AddWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MitraService_AddWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MitraServiceServer).AddWorktree(ctx, req.(*AddWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MitraService_ListWorktrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorktreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MitraServiceServer).ListWorktrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MitraService_ListWorktrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MitraServiceServer).ListWorktrees(ctx, req.(*ListWorktreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MitraService_ServiceDesc is the grpc.ServiceDesc for MitraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MitraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MitraService",
	HandlerType: (*MitraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRepos",
			Handler:    _MitraService_ListRepos_Handler,
		},
		{
			MethodName: "AddRepo",
			Handler:    _MitraService_AddRepo_Handler,
		},
		{
			MethodName: "AddWorktree",
			Handler:    _MitraService_AddWorktree_Handler,
		},
		{
			MethodName: "ListWorktrees",
			Handler:    _MitraService_ListWorktrees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/mitra.proto",
}
