// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/repo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_internal_proto_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_internal_proto_repo_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_internal_proto_repo_proto protoreflect.FileDescriptor

const file_internal_proto_repo_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/repo.proto\x12\x05proto\">\n" +
	"\x04Repo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04pathB\x16Z\x14mitra/internal/protob\x06proto3"

var (
	file_internal_proto_repo_proto_rawDescOnce sync.Once
	file_internal_proto_repo_proto_rawDescData []byte
)

func file_internal_proto_repo_proto_rawDescGZIP() []byte {
	file_internal_proto_repo_proto_rawDescOnce.Do(func() {
		file_internal_proto_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_repo_proto_rawDesc), len(file_internal_proto_repo_proto_rawDesc)))
	})
	return file_internal_proto_repo_proto_rawDescData
}

var file_internal_proto_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_repo_proto_goTypes = []any{
	(*Repo)(nil), // 0: proto.Repo
}
var file_internal_proto_repo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_repo_proto_init() }
func file_internal_proto_repo_proto_init() {
	if File_internal_proto_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_repo_proto_rawDesc), len(file_internal_proto_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_repo_proto_goTypes,
		DependencyIndexes: file_internal_proto_repo_proto_depIdxs,
		MessageInfos:      file_internal_proto_repo_proto_msgTypes,
	}.Build()
	File_internal_proto_repo_proto = out.File
	file_internal_proto_repo_proto_goTypes = nil
	file_internal_proto_repo_proto_depIdxs = nil
}
