// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/repo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_internal_proto_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_internal_proto_repo_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposRequest) Reset() {
	*x = ListReposRequest{}
	mi := &file_internal_proto_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposRequest) ProtoMessage() {}

func (x *ListReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposRequest.ProtoReflect.Descriptor instead.
func (*ListReposRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_repo_proto_rawDescGZIP(), []int{1}
}

type ListReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repo                `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposResponse) Reset() {
	*x = ListReposResponse{}
	mi := &file_internal_proto_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposResponse) ProtoMessage() {}

func (x *ListReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposResponse.ProtoReflect.Descriptor instead.
func (*ListReposResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_repo_proto_rawDescGZIP(), []int{2}
}

func (x *ListReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

var File_internal_proto_repo_proto protoreflect.FileDescriptor

const file_internal_proto_repo_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/repo.proto\x12\x05proto\">\n" +
	"\x04Repo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x12\n" +
	"\x10ListReposRequest\"6\n" +
	"\x11ListReposResponse\x12!\n" +
	"\x05repos\x18\x01 \x03(\v2\v.proto.RepoR\x05repos2M\n" +
	"\vRepoService\x12>\n" +
	"\tListRepos\x12\x17.proto.ListReposRequest\x1a\x18.proto.ListReposResponseB\x16Z\x14mitra/internal/protob\x06proto3"

var (
	file_internal_proto_repo_proto_rawDescOnce sync.Once
	file_internal_proto_repo_proto_rawDescData []byte
)

func file_internal_proto_repo_proto_rawDescGZIP() []byte {
	file_internal_proto_repo_proto_rawDescOnce.Do(func() {
		file_internal_proto_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_repo_proto_rawDesc), len(file_internal_proto_repo_proto_rawDesc)))
	})
	return file_internal_proto_repo_proto_rawDescData
}

var file_internal_proto_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_repo_proto_goTypes = []any{
	(*Repo)(nil),              // 0: proto.Repo
	(*ListReposRequest)(nil),  // 1: proto.ListReposRequest
	(*ListReposResponse)(nil), // 2: proto.ListReposResponse
}
var file_internal_proto_repo_proto_depIdxs = []int32{
	0, // 0: proto.ListReposResponse.repos:type_name -> proto.Repo
	1, // 1: proto.RepoService.ListRepos:input_type -> proto.ListReposRequest
	2, // 2: proto.RepoService.ListRepos:output_type -> proto.ListReposResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_repo_proto_init() }
func file_internal_proto_repo_proto_init() {
	if File_internal_proto_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_repo_proto_rawDesc), len(file_internal_proto_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_repo_proto_goTypes,
		DependencyIndexes: file_internal_proto_repo_proto_depIdxs,
		MessageInfos:      file_internal_proto_repo_proto_msgTypes,
	}.Build()
	File_internal_proto_repo_proto = out.File
	file_internal_proto_repo_proto_goTypes = nil
	file_internal_proto_repo_proto_depIdxs = nil
}
